name: Playwright Tests

on:
  push:
    branches:
      - main
    paths:
      - '**/*.ts'
      - '**/*.js'
      - 'package.json'
      - 'package-lock.json'
  pull_request:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set working directory  # Explicitly set the working directory
        run: cd /Users/timeo/deepFocus/deepWork

      - name: Install system dependencies for node-gyp
        run: |
          brew install cmake
          brew install pkg-config
          brew install python3

      - name: Install dependencies
        run: npm install

      - name: Run Playwright tests
        run: npm run test:e2e
